### ISSUE TITLE
Librocket datagrids: 100% width is larger than the given space

### ISSUE THREAD

**Issue by Veyrdite** [Unvanquished/Unvanquished#396]
Note the width of the rows given for humans: larger than the given space
![unvanquished_2014-08-04_220408_000](https://cloud.githubusercontent.com/assets/6168874/3796832/cbe764c6-1bcf-11e4-8785-f709ec9e1086.jpg)
For aliens this was fixed by omitting the width="" for the last column.  Setting the widths up to add to 99% also works.

``````
<half>
    <teamname> Humans </teamname>
    <teambox class="human">
        <datagrid source="playerList.humans" id="humans">
            <col fields="num" formatter="GearOrReady" width="8%"></col>
            <col fields="num" formatter="PlayerName" width="47%">Name</col>
            <col fields="score" width="15%">Score</col>
            <col fields="time" width="15%">Time</col>
            <col fields="ping" width="15%">Ping</col>
        </datagrid>
    </teambox>
</half>```
``````

**Comment by bmorel** [comment]
Rocket. Move to RMLui in 0.53. To check.

**Comment by necessarily-equal** [comment]
![image](https://user-images.githubusercontent.com/59283660/202756549-b1b3f536-71a8-4c09-b7c3-fe57d5b42903.png)

A similar bug was fixed when moving to RmlUI. I think this issue is fixed.

**Comment by slipher** [comment]
In fact, the move to RmlUi triggered some instances of this bug IIRC

**Comment by illwieckz** [comment]
Yeah, I remember having faced variants of this one recently, as 50% +50% may not be 100% because of _floats_:

- https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/pull/142
- https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/pull/143

**Comment by illwieckz** [comment]
The bug is still alive with RmlUi, though it is low priority and very easy to work around.

**Comment by necessarily-equal** [comment]
I'm ok with keeping a bug around, but I'm remilestoning it for post-beta then
