### ISSUE TITLE
demo player does not load extrapacks (must play a game before)

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#540]
Hi, If I run server like that: (with some `mod-devserver` pk3 in `pkg/dev`)

```
daemonded +set fs_extrapaks dev/mod-devserver
```

Then I connect the `daemon` client to this server and record a demo.

Then I play the demo like that:

```
daemon +demo demoname
```

Or like that:

```
daemon +set fs_extrapaks dev/mod-devserver +demo name
```

In both cases I get some model mismatch like that (here rocket pods rendered as armoury):

![model mismatch](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-01-25_022201_000.jpg)

The only way to load the demo correctly is to load a game joining the server first, then playing the demo.

So, it seems that playing a demo don't use extrapacks until you play with these extrapacks.

At Unvanquished startup, if you play a game with extrapacks first, demo will use them, if you play a demo first, demo will not use them even if you pass them as arguments at runtime.

You can reproduce playing this demo at Unvanquished startup: [demo file](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/demos/unv035git.perseus-rocket-dodge-in-hell.1-dretch-versus-40-rocket-pods.dm_86).
If you want to play this demo correctly, you can connect to `gg.illwieckz.net:27960` first at Unvanquished startup then play the demo.

**Comment by Viech** [comment]
The proper method to handle this is not to require the user to manually set `fs_extrapaks` but to have the demo require the same pk3s that it was recorded with. I'd be fine with an option to bypass this requirement (similiar to how you can connect to a server that loads a pk3dir, which is normally not possible for similiar reasons).

**Comment by DolceTriade** [comment]
Does the demo even store the pak list? I'm not sure it does...

**Comment by Viech** [comment]
If not, it needs to.

**Comment by Kangz** [comment]
CL_Record writes the config strings in the demo file, and in the SystemInfo config string, sv_paks has the server paks. I think a very small change is needed in CL_SystemInfoChanged will fix this (it explicitely check for a demo and then loads only the map, otherwise it looks up sv_paks and loads the paks).

If noone fixes it soon, I'll do it (can't right now)

**Comment by DolceTriade** [comment]
The reason I did it that way was that sv_paks was empty.

**Comment by DolceTriade** [comment]
Turns out it does store sv_paks... However, pk3dirs will break it.

**Comment by Kangz** [comment]
Should be fixed by 60de58ef08c5a8c71e39a7bf7600ce8d6efbba1e and earlier commits, @illwieckz can you confirm it fixes things for you?

**Comment by Kangz** [comment]
http://pastebin.com/LXntfbg2 shows it isn't fixed yet

**Comment by DolceTriade** [comment]
It's fixed with Amanieu's commit. https://github.com/Unvanquished/Unvanquished/commit/60de58ef08c5a8c71e39a7bf7600ce8d6efbba1e

**Comment by Kangz** [comment]
Are you sure? There might have been a confusion, the log file I linked was from @illwieckz testing after Amanieu's commits.

**Comment by DolceTriade** [comment]
Looks fixed to me...
```
Loading pak '/home/illwieckz/.unvanquished/pkg/dev/mod-devserver_2015-01-18-1907-viech.pk3'...
Loading pak '/home/illwieckz/.unvanquished/pkg/dev/rocketpod_2015-01-11-1600-viech.pk3'...
Loading pak '/home/illwieckz/.unvanquished/pkg/dev/spiker_2015-01-18-1855-viech.pk3'...
```

**Comment by illwieckz** [comment]
Looks not fixed to me (the log above is the log of this play):
![ko](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-01-29_211853_000.jpg)

Normally you must get that:
![ok](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-01-29_212122_000.jpg)

It seems that extrapacks are loaded but not used.

**Comment by Viech** [comment]
I don't see how 608018e and 60de58e should fix the actual issue, which is that demos don't seem to load the packages from the remote (server sent) package list. Those commits seem to only add another option, which is loading extra packages in addition to those. However, despite the issue title being specifically about extra packages, the fact that @illwieckz needs/wants to manually specify extra paks at all is the bug here.

**Comment by illwieckz** [comment]
> Those commits seem to only add another option, which is loading extra packages in addition to those.

If the option is `+set fs_extrapaks`, it does not works too, right now while running last master and launching unvanquished like that:

```
./daemon +set fs_extrapaks dev/mod-devserver +set fs_libpath . +set fs_basepath /var/games/unvanquished +demo demoname 
```

I get that:

![bug](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-01-31_142637_000.jpg)

**Comment by Viech** [comment]
I didn't say that the commits in questions *worked*, I just said they're not trying to fix what I see as the core issue. :wink:

**Comment by DolceTriade** [comment]
Those commits were for another issue relating to demoes. I forgot to link kangz's commit which was the initial attempted fix. https://github.com/Unvanquished/Unvanquished/commit/f93715583f050ae7edbd9ac68094536d6f488529

**Comment by Amanieu** [comment]
Is this issue resolved on the latest release?

**Comment by illwieckz** [comment]
I will try yes.

**Comment by illwieckz** [comment]
Hem, to test on the latest release I need an extrapack for the latest release…

**Comment by Viech** [comment]
Can you test with the 0.35.1 multiplatform package, found [here](https://cdn.unvanquished.net/unvanquished_0.35.1.torrent) as a torrent or [here](https://sourceforge.net/projects/unvanquished/files/Universal_Zip/unvanquished_0.35.1.zip/download) as a web download? (If you have a 0.35.0 version and are not on windows, it should work as well.) Otherwise I could also make code changes and create a pk3 that makes the issue visible.

**Comment by illwieckz** [comment]
Yes I will try with 0.36.0 binary and 0.35.0 data

**Comment by Viech** [comment]
I don't think this will work as the network protocol is incompatible between 0.35.0/1 and 0.36.0. Better use a vanilla Alpha 35 setup to test.

**Comment by illwieckz** [comment]
Amanieu also invited me to change a texture from one model, it's an easy way to see which package is used, and I can do this with a vanilla 0.36.0.

**Comment by Amanieu** [comment]
Does this problem still happen? I seem to recall this being fixed a while ago.

**Comment by illwieckz** [comment]
I still need to test it.

**Comment by Viech** [comment]
The problem is fixed if and only if demos store the package list and require clients to load it in the same way as the client was required to load them when connecting to the server initially.

**Comment by Amanieu** [comment]
This should be the case since the pak list is stored in the demo in systeminfo.

**Comment by Amanieu** [comment]
Closing, this should have been fixed a while back
