### ISSUE TITLE
Weapon range, damage, fire rate information displayed in buy menu are incorrect.

### ISSUE THREAD

**Issue by Viech** [Unvanquished/Unvanquished#582]
The three distinct bar graphs are literally all interpretations of the weapon number. The correct values are never passed to the UI to begin with.

**Comment by DolceTriade** [comment]
It seems correct to me. Changing range to precision is fine, but what else do you want to change?

**Comment by Viech** [comment]
Can you elaborate on the "it seems correct to me"? At the time when I wrote the issue, I was looking at the code and the data that every single bar graph displayed appeared to be the weapon number, not the data they were supposed to display. Either this was fixed or it's still entirely wrong (which seems likely given that on current master the shotgun has the highest possible fire rate and the chaingun does about eight time as much damage as the rifle). Apart from that and range → precision is the only thing I'd change.

**Comment by DolceTriade** [comment]
Maybe the values need to be modified, but they are reporting the values that were set.

**Comment by Viech** [comment]
Those should not be hardcoded. Use the actual values.

**Comment by harmonise** [comment]
Note: Relevant file is now located at https://github.com/Unvanquished/Unvanquished/blob/master/src/cgame/cg_rocket_dataformatter.cpp#L245

**Comment by bmorel** [comment]
Actual game numbers are still not used, or there is something buggy for at least the shotgun:

![2021-10-18-210758_1366x758_scrot](https://user-images.githubusercontent.com/1316300/137792151-a1941a66-cca5-44e1-abb0-0a99897f758b.png)
![2021-10-18-210805_1366x758_scrot](https://user-images.githubusercontent.com/1316300/137792157-91d4b0e0-148f-421f-8325-7a45122bce92.png)

Here, shotgun is compared to mass driver.

In practice:

* they have exact same fire rate (1s between each shot, 2s reload time)
* shotgun have a much higher DpS at optimal range (55 damages per shot vs 40)

Here, we can see that the shotgun have an extremely high fire rate compared to mass driver (and, in fact, to any weapon except the pain saw).
Maybe this is triggered by the amount of pellets in the shotgun, but that would still be wrong, misleading, and thus a bug.

As for damages, those screen shows that shotgun deals less damages: again, this is wrong.

**Comment by bmorel** [comment]
Note that this is likely easy to fix, one only have to loop between each weapons, get the maximum and minimum value of each category, add a margin, and build numbers between 0 and 100 from those.

Code is around here: https://github.com/Unvanquished/Unvanquished/blob/master/src/cgame/cg_rocket_dataformatter.cpp#L136-L203

**Comment by slipher** [comment]
For many weapon statistics, the value is either meaningless or has an unclear interpretation. For example, what is the fire rate or damage rate of the Lucifer Cannon? There is a hard-coded table because a lot of values are not possible to find automatically.

Also "Range" doesn't correspond to any simple number in the code AFAIK.

**Comment by bmorel** [comment]
The luci primary attack is indeed a problem, and "range" is, as you said, not a real thing in most cases, instead, accuracy could probably be used.

**Comment by bmorel** [comment]
It has to be noted that currently, betterai mod uses the range values to make bots walk backward until they reach limit when they attack a building.
Behavior is... pretty interesting, and a better information would be quite useful for weapons like chaingun (which probably have something like "infinite" and chaingun (which in practice have "infinite": `shotgun.attr.cfg:range 98304 // ( 8192 * 12 )` is there is any map with a diagonal wider than 100K qu?)
