### ISSUE TITLE
Regressions in the build systems after the decoupling

### ISSUE THREAD

**Issue by Kangz** [Unvanquished/Unvanquished#794]
- [ ] Building the NaCl VMs doesn't work on windows, it seems to not be using the NaCl CMake toolchain
- [ ] Building the native DLL / exe VMs on Windows is slow (seems to be using only one process)
- [ ] VMs are not using PCH anymore
- [ ] Compiling with Ninja doesn't show the output of building the NaCl VMs
- [ ] Compiling with Makefiles shows the percentage go to 100% twice (minor issue)
- [ ] Not all compile flags are forwarded to the building of NaCl VMs

@TimePath this is the list of things I have noticed.

**Comment by Amanieu** [comment]
The last issue is fixed in my branch deps_wip

**Comment by Amanieu** [comment]
VMs now use PCH (not tested on msvc though)

**Comment by Amanieu** [comment]
> Compiling with Ninja doesn't show the output of building the NaCl VMs
This is because Ninja will only show the output of a subcommand once it has completed, to avoid messages of 2 parallel commands getting mixed up.

There's no real way around that: we need to invoke a sub-make because we run cmake with a different toolchain configuration for NaCl.

**Comment by Amanieu** [comment]
Another thing to add to the list: make clean doesn't clean nacl vms

**Comment by Amanieu** [comment]
NaCl VMs should now work on MSVC, but I wasn't able to fully test them

**Comment by TimePath** [comment]
keep an eye on https://cmake.org/Bug/view.php?id=14539

**Comment by bmorel** [comment]
> keep an eye on https://cmake.org/Bug/view.php?id=14539

> 2016-06-10 14:31	Kitware Robot	Status	resolved => closed

**Comment by slipher** [comment]
@bmorel It says that all issues are closed because the issue tracker is no longer issued. Pretty sure you still can't have multiple toolchains.

**Comment by bmorel** [comment]
Indeed, and here is the current "report": https://gitlab.kitware.com/cmake/cmake/-/issues/14539 (it's empty, except for the link to original)
